// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieves memory usage, goroutine count, version, hostname, Go runtime version, and OS.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Get health data",
                "responses": {
                    "200": {
                        "description": "Health data successfully retrieved",
                        "schema": {
                            "$ref": "#/definitions/health.Model"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/web.ApiError"
                        }
                    }
                }
            }
        },
        "/relays": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns name, state (on/off) and description for every configured relay.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relay"
                ],
                "summary": "List all relays",
                "responses": {
                    "200": {
                        "description": "List of all relays",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/app.HTTPResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/web.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/web.ApiError"
                        }
                    }
                }
            }
        },
        "/relays/{name}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns name, state (on/off) and description for the given relay.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relay"
                ],
                "summary": "Get relay state",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Relay name (e.g. relay1)",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Relay state",
                        "schema": {
                            "$ref": "#/definitions/app.HTTPResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/web.ApiError"
                        }
                    },
                    "404": {
                        "description": "Relay not found",
                        "schema": {
                            "$ref": "#/definitions/web.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/web.ApiError"
                        }
                    }
                }
            }
        },
        "/relays/{name}/{state}": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Sets the state of a specific relay by name.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relay"
                ],
                "summary": "Set relay state",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Relay name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Relay state (on/off)",
                        "name": "state",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Relay state successfully set",
                        "schema": {
                            "$ref": "#/definitions/app.HTTPResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid state",
                        "schema": {
                            "$ref": "#/definitions/web.ApiError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/web.ApiError"
                        }
                    },
                    "404": {
                        "description": "Relay not found",
                        "schema": {
                            "$ref": "#/definitions/web.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/web.ApiError"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Returns the current application name and version. No authentication required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Get application version and name",
                "responses": {
                    "200": {
                        "description": "Application version and name",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "app": {
                                    "type": "string"
                                },
                                "appVersion": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.Display": {
            "type": "object",
            "properties": {
                "color": {
                    "description": "pilot light colour when on: green, red or amber",
                    "type": "string"
                },
                "label": {
                    "description": "the relay name unless configured",
                    "type": "string"
                },
                "offText": {
                    "description": "word for the off state, OFF when empty",
                    "type": "string"
                },
                "onText": {
                    "description": "word for the on state, ON when empty",
                    "type": "string"
                }
            }
        },
        "app.HTTPResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "display": {
                    "$ref": "#/definitions/app.Display"
                },
                "gpio": {
                    "type": "integer"
                },
                "lastChange": {
                    "description": "absent when unknown",
                    "allOf": [
                        {
                            "$ref": "#/definitions/app.LastChangeInfo"
                        }
                    ]
                },
                "name": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "app.LastChangeInfo": {
            "type": "object",
            "properties": {
                "ageSeconds": {
                    "description": "seconds since Time, by the Pi's clock",
                    "type": "number"
                },
                "client": {
                    "description": "IP address of the API client",
                    "type": "string"
                },
                "host": {
                    "description": "reverse DNS name of the client, when it has one",
                    "type": "string"
                },
                "source": {
                    "description": "api, or start when relayhat switched it on start",
                    "type": "string"
                },
                "time": {
                    "description": "RFC 3339, in the Pi's time zone",
                    "type": "string"
                }
            }
        },
        "health.Model": {
            "type": "object",
            "properties": {
                "app": {
                    "description": "Application name (MODULE)",
                    "type": "string"
                },
                "appVersion": {
                    "description": "Current version of the application",
                    "type": "string"
                },
                "goVersion": {
                    "description": "Go runtime version",
                    "type": "string"
                },
                "heapAllocBytes": {
                    "description": "Allocated heap memory in bytes",
                    "type": "integer"
                },
                "hostname": {
                    "description": "Machine name where the app runs",
                    "type": "string"
                },
                "numGoroutines": {
                    "description": "Current number of active goroutines",
                    "type": "integer"
                },
                "os": {
                    "description": "Operating system name",
                    "type": "string"
                },
                "sysMemoryBytes": {
                    "description": "Total memory obtained from the OS",
                    "type": "integer"
                },
                "timestamp": {
                    "description": "UTC timestamp when health info was collected (RFC3339)",
                    "type": "string"
                },
                "uptimeSeconds": {
                    "description": "Application uptime in seconds",
                    "type": "number"
                }
            }
        },
        "web.ApiError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
